nameOverride: shireburn-employee-management
namespace:
  create: true
  name: shireburn-employee-management

host: shireburn-employee-management.example.com

imagePullSecrets: []

image:
  repository: ghcr.io/and1rew132/shireburn-platform
  tag: main
  pullPolicy: Always

app:
  replicaCount: 1
  port: 3000
  publicAppName: Shireburn Platform - Employee Management
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

secrets:
  name: shireburn-employee-management-secrets
  existingSecret: ""
  sessionSecret: ""

database:
  existingSecret: ""
  urlKey: DATABASE_URL
  url: ""

postgres:
  enabled: false
  image: postgres:17-alpine
  database: shireburn_employee_management
  username: shireburn_employee_management
  password: ""
  persistence:
    size: 1Gi

ingress:
  enabled: true
  entryPoints:
    - web
    - websecure
  certResolver: myresolver
