nameOverride: shireburn-employee-management
namespace:
  create: true
  name: shireburn-employee-management

host: shireburn-employee-management.andrewazzopardi.dev

imagePullSecrets: []

image:
  repository: ghcr.io/and1rew132/purple-cross-employee-dashboard
  tag: latest
  pullPolicy: Always

app:
  replicaCount: 1
  port: 3000
  publicAppName: Shireburn Platform - Employee Management
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

secrets:
  name: shireburn-employee-management-secrets
  databaseUrl: ""
  sessionSecret: ""

postgres:
  enabled: true
  image: postgres:17-alpine
  database: purple_cross
  username: purple_cross
  password: change-me
  persistence:
    size: 1Gi

ingress:
  enabled: true
  entryPoints:
    - web
    - websecure
  certResolver: myresolver
