apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  DATABASE_URL: {{ default (printf "postgresql://%s:%s@%s-postgres:5432/%s?schema=public" .Values.postgres.username .Values.postgres.password .Values.nameOverride .Values.postgres.database) .Values.secrets.databaseUrl | quote }}
  SESSION_SECRET: {{ required "secrets.sessionSecret is required" .Values.secrets.sessionSecret | quote }}
